% Runs the neural discrimination for cross-fostered L
brainregion = 'bengalese_L';
fname = 'bf_fieldL.mat';

% All the data files pasted from the Excel file
fieldL_bf = { ...
{'pi05', '2_B'}, ...
{'pi05', '4_B'}, ...
{'pi05', '5_B'}, ...
{'pi05', '6_B'}, ...
{'pi05', '8_B'}, ...
{'pi05', '11_B'}, ...
{'g08', '6_B'}, ...
{'gg1717', '5_B'}, ...
{'pipi0607', '3_B'}, ...
{'pipi0607', '4_B'}, ...
{'pipi0607', '5_B'}, ...
{'pipi0607', '6_B'}, ...
{'pipi0607', '7_B'}, ...
{'pipi0607', '8_B'}, ...
{'pipi0607', '9_B'}, ...
{'pipi0607', '10_B'}, ...
{'g03', '3_B'}, ...
{'g03', '5_B'}, ...
{'g03', '6_B'}, ...
{'g03', '7_B'}, ...
{'g03', '8_B'}, ...
{'g03', '9_B'}, ...
{'g03', '12_B'}, ...
{'lblb0505', '3_B'}, ...
{'lblb0505', '4_B'}, ...
{'lblb0505', '5_B'}, ...
{'lblb0505', '6_B'}, ...
{'lblb0505', '7_B'}, ...
{'pi07', '3_B'}, ...
{'pi07', '4_B'}, ...
{'pi07', '5_B'}, ...
{'pi07', '6_B'}, ...
{'pi07', '7_B'}, ...
{'pi07', '8_B'}, ...
{'pi07', '9_B'}, ...
{'pi07', '10_B'}, ...
{'g06', '10_B'}, ...
{'g06', '9_B'}, ...
{'gg1717', '7_B'}, ...
{'gg1717', '8_B'}, ...
{'gg1717', '9_B'}, ...
{'gg1717', '6_B'}, ...
};

% Allocate space for output values
number_cells = length(fieldL_bf);

% Allocate file names for the temp results
%done_bengalese_name = cell(1,number_cells);
done_conspecific_name = cell(1,number_cells);
%done_flatrip_name = cell(1,number_cells);

for nc=1:number_cells
    %stimtype = 'bengalese';
    %done_bengalese_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
    stimtype = 'conspecific';
    done_conspecific_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
    %stimtype = 'flatrip';
    %done_flatrip_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
end


not_done = 1;
n_loop = 0;
njobs = 0;
% Add jobs to queue until done
while not_done
    not_done = 0;
    for nc=1:number_cells
        %stimtype = 'bengalese';
        %if (exist(done_bengalese_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
        stimtype = 'conspecific';
        if (exist(done_conspecific_name{nc},'file') == 0)
            the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
            the_comment = sprintf('ND%s%s%s%s',fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
            njobs = njobs +1;
            qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
            not_done = 1;
            if n_loop
                fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
            end
        end
        %stimtype = 'flatrip';
        %if (exist(done_flatrip_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',fieldL_bf{nc}{1}, brainregion, fieldL_bf{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
    end
    pause(30*60); % pause for 30 minutes
    n_loop = n_loop +1;
end

% Clean the queue
for ij=1:njobs
    silent_dbdeletequeue(qid_submitted(ij));
end

% Print the results to a text file
%nstim = 3;
nstim = 1;
%stim_type = {'bengalese', 'conspecific', 'flatrip'};
stim_type = {'conspecific'};
all_outputs = cell(number_cells, nstim);


for nc=1:number_cells
    %load(done_bengalese_name{nc});
    %all_outputs{nc,1} = outputs;
    
    load(done_conspecific_name{nc});
    all_outputs{nc,2} = outputs;
    
    %load(done_flatrip_name{nc});
    %all_outputs{nc,3} = outputs;
end
save(fname, 'nstim', 'stim_type', 'fieldL_bf', 'all_outputs');

