% This file runs the matlab programs.

cd /data/sarah/mld-l-strf/oo1020/1_A/con;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/1_A/songrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/1_A/flatrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_A/con;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_B/con;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_A/songrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_B/songrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_A/flatrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/3_B/flatrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_A/con;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_B/con;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_A/songrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_B/songrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_A/flatrip;
filters2;
clear;
cd /data/sarah/mld-l-strf/oo1020/4_B/flatrip;
filters2;
clear;