% Runs the neural discrimination for normal L
brainregion = 'maybe_L';
fname = 'zfnormal_fieldL.mat';

% All the data files pasted from the Excel file
fieldL_normal = { ...
     {'yy0304', '3_B' }, ... 
     {'blahpi0303', '5_B'}, ...
     {'blahpi0303', '7_B' }, ...
     {'blahpi0303', '8_B' }, ...
     {'blahpi0303', '9_B' }, ...
     {'blahpi0303', '10_B' }, ...
    {'publu0717', '3_B' }, ...
    {'publu0717', '6_B' }, ...
    {'publu0717', '7_B' }, ...
    {'publu0717', '9_B' }, ...
    {'lghp1616', '4_B' }, ...
    {'lghp1616', '5_B' }, ...
    {'lghp1616', '6_B' }, ...
    {'lghp1616', '7_B' }, ...
    {'lghp1616', '8_B' }, ...
    {'lghp1616', '9_B' }, ...
    {'lghp1616', '10_B' }, ...
    {'pipu1018', '1_B' }, ... 
    {'pipu1018', '2_B' }, ... 
    {'pipu1018', '3_B' }, ...
    {'pipu1018', '4_B' }, ...
    {'pipu1018', '6_B' }, ...
    {'pipu1018', '7_B' }, ...
    {'pipu1018', '11_B' }, ... 
    {'lblb0808', '3_B' }, ...
    {'gg0304', '4_B' }, ...
    {'gg0304', '6_B' }, ...
    {'gg0304', '8_B' }, ...
    {'gg0304', '9_B' }, ...
    {'gg0304', '10_B' }, ...
    {'pipu0617', '3_B' }, ...
    {'pipu0617', '4_B' }, ...
    {'pipu0617', '5_B' }, ...
    {'pipu0617', '7_B' }, ...
    {'pipu0617', '8_B' }, ...
    {'pipu0617', '9_B' }, ...
    {'pipu0617', '10_B' }, ...
    {'yg0111', '2_B' }, ...
    {'yg0111', '3_B' }, ...
    {'yg0111', '4_B' }, ...
    {'yg0111', '5_B' }, ...
    {'yg0111', '6_B' }, ...
    {'yg0111', '7_B' }, ...
    {'yg0111', '8_B' }, ...
    {'yg0111', '9_B' }, ...
    {'yg0111', '10_B' }, ...
    {'yg0331', '2_B' }, ...
    {'yg0331', '3_B' }, ...
    {'yg0331', '4_B' }, ...
    {'yg0331', '5_B' }, ...
    {'yg0331', '8_B' }, ...
    {'yg0331', '9_B' }, ...
    {'yg0331', '10_B' }, ...
    {'yg0616', '8_B' }, ...
    {'yg0616', '9_B' }, ...
    {'yg0616', '10_B' }, ...
    {'yg0616', '11_B' }, ...
    {'yg0616', '12_B' }, ...
    {'blublu9394', '2_B' }, ...
    {'blublu9394', '3_B' }, ...
    {'blublu9394', '4_B' }, ...
    {'blublu9394', '5_B' }, ...
    {'blublu9394', '7_B' }, ...
    {'blahpi0808', '4_B' }, ...
    {'blahpi0808', '6_B' }, ... 
    {'blahpi0808', '7_B' } };

number_cells = length(fieldL_normal);


% Allocate file names for the temp results
%done_bengalese_name = cell(1,number_cells);
done_con_name = cell(1,number_cells);
%done_mlnoise_name = cell(1,number_cells);

for nc=1:number_cells
    %stimtype = 'bengalese';
    %done_bengalese_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
    stimtype = 'conspecific';
    done_con_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
    %stimtype = 'flatrip';
    %done_mlnoise_name{nc} = sprintf('%s_%s_%s_%s.mat' , fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
end

not_done = 1;
n_loop = 0;
njobs = 0;
% Add jobs to queue until done
while not_done
    not_done = 0;
    for nc=1:number_cells
        %stimtype = 'bengalese';
        %if (exist(done_bengalese_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/fet/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
        stimtype = 'conspecific';
        if (exist(done_con_name{nc},'file') == 0)
            the_command = sprintf('cd(''/auto/fhome/fet/matlab/Neural Discrimination/''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
            the_comment = sprintf('ND%s%s%s%s',fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
            njobs = njobs +1;
            qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
            not_done = 1;
            if n_loop
                fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
            end
        end
        %stimtype = 'flatrip';
        %if (exist(done_mlnoise_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/fet/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',fieldL_normal{nc}{1}, brainregion, fieldL_normal{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
    end
    if not_done
        pause(4*40*60); % pause for four hours before resubmitting the same jobs...
    end
    n_loop = n_loop +1;
end

% Clean the queue
for ij=1:njobs
    silent_dbdeletequeue(qid_submitted(ij));
end

% Make a single data base
% Print the results to a text file
%nstim = 3;
nstim = 1;
%stim_type = {'bengalese', 'conspecific', 'flatrip'};
stim_type ={'conspecific'};
all_outputs = cell(number_cells, nstim);

for nc=1:number_cells
    %load(done_bengalese_name{nc});
    %all_outputs{nc,1} = outputs;
    
    load(done_con_name{nc});
    all_outputs{nc,2} = outputs;
    
    %load(done_mlnoise_name{nc});
    %all_outputs{nc,3} = outputs;
end
save(fname, 'nstim', 'stim_type', 'fieldL_normal', 'all_outputs');
