mysql('open','database.fet.berkeley.edu','cluster_analysis','cluster');

classresp_ids = struct2array(mysql(['SELECT response_id ',...
					   'FROM physiology.responses ',...
					   'NATURAL JOIN physiology.presentations ',...
					   'WHERE type = ''class'';']));
mysql('close');
n_classresps = length(classresp_ids);

for jj = 1:n_classresps:
	queue_str = sprintf(['addpath(''/auto/fhome/channing/workspace/tlab/',...
						 'tlab/lib/discrimination'');',...
						 'neural_discrimination_db(%d);'],classresp_ids(jj));
	dbaddqueuemaster(queue_str);
end