%These are names of cells that I had "good" STRFs for wn birds
%note that wnstrf_names is for mlnoise analysis and this one is using
%responses to conspecific song...
 
clear all;
used_names = cell(1, 27); %hard-coded, 31 is the number of good strfs for wn project
used_names = { ...
    {'wnmale1', '5' }, ... %wnmale1 is 90 days old
    {'wnmale1', '6' }, ... %wnmale1 is 90 days old
    {'wnmale4', '9' }, ... 
    {'wnmale6', '8' }, ... 
    {'wnmale6', '9' }, ... 
    {'wnmale6', '10' }, ... 
    {'wnmale6', '11' }, ... 
    {'wnmale7', '11' }, ... 
    {'wnmale7', '15' }, ... 
    {'wnmale8', '1' }, ... 
    {'wnmale8', '2' }, ... 
    {'wnmale8', '3' }, ... 
    {'wnfemale1', '6' }, ... 
    {'wnfemale1', '7' }, ... 
    {'wnfemale1', '8' }, ... 
    {'wnfemale1', '9' }, ... 
    {'wnfemale4', '12' }, ... 
    {'wnfemale4', '13' }, ... 
    {'wnfemale5', '5' }, ... 
    {'wnfemale5', '7' }, ... 
    {'wnfemale5', '8' }, ... 
    {'wnfemale5', '9' }, ... 
    {'wnfemale5', '12' }, ... 
    {'wnfemale6', '5' }, ... 
    {'wnfemale6', '6' }, ... 
    {'wnfemale7', '13' }, ... 
    {'wnfemale8', '6' }};
    %{'wnfemale3', '5' }, ... %wnfemale3 is 8 months old
    %{'wnfemale3', '7' }, ... %wnfemale3 is 8 months old
    %{'wnfemale3', '8' }, ... %wnfemale3 is 8 months old
    %{'wnfemale3', '11' }}; %wnfemale3 is 8 months old
save used_names;

strfs = cell(1, length(used_names));
for nc = 1:length(used_names)
    direct = fullfile('/auto/fdata/noopur/wn/strfdir',used_names{nc}{1},used_names{nc}{2},'Conspecific/Output');
    cd(direct)
    load best_strf.mat;
    strfs{nc} = strf;
end

cd '/auto/fhome/pgill/clustering_STRFs/';
save strfs;