% Runs the neural discrimination for xf mld
brainregion = 'XFosteredZF_mld';
fname = 'xf_mld.mat';

% All the data files pasted from the Excel file
mld_xf = { ...
{'lblb0303', '2_A'}, ...
{'lblb0303', '3_A'}, ...
{'lblb0303', '4_A'}, ...
{'lblb0303', '5_A'}, ...
{'lblb0303', '6_A'}, ...
{'lblb0303', '7_A'}, ...
{'lblb0303', '8_A'}, ...
{'lblb0303', '9_A'}, ...
{'lblb0303', '10_A'}, ...
{'lblb0303', '11_A'}, ...
{'hpw0411', '3_A'}, ...
{'hpw0411', '4_A'}, ...
{'hpw0411', '5_A'}, ...
{'hpw0411', '6_A'}, ...
{'hpw0411', '7_A'}, ...
{'hpw0411', '8_A'}, ...
{'hpw0411', '9_A'}, ...
{'hpw0411', '10_A'}, ...
{'hpw0411', '11_A'}, ...
{'lblb0808', '3_A'}, ...
{'lblb0808', '6_A'}, ...
{'lblb0808', '7_A'}, ...
{'lblb0808', '8_A'}, ...
{'lblb0808', '9_A'}, ...
{'lblb0808', '10_A'}, ...
{'ww1414', '2_A'}, ...
{'ww1414', '3_A'}, ...
{'ww1414', '4_A'}, ...
{'ww1414', '6_A'}, ...
{'ww1414', '7_A'}, ...
{'ww1414', '8_A'}, ...
{'ww1414', '9_A'}, ...
{'ww1414', '10_A'}, ...
{'hpidg0712', '2_A'}, ...
{'hpidg0712', '3_A'}, ...
{'hpidg0712', '4_A'}, ...
{'hpidg0712', '5_A'}, ...
{'hpidg0712', '6_A'}, ...
{'hpidg0712', '7_A'}, ...
{'hpidg0712', '8_A'}, ...
{'hpidg0712', '9_A'}, ...
{'ww1212', '4_A'}, ...
{'ww1212', '9_A'}, ...
{'ww1212', '10_A'}, ...
{'ww1212', '11_A'}, ...
{'ww1212', '12_A'}, ...
{'ww1212', '13_A'} };

% Allocate space for output values
number_cells = length(mld_xf);



% Allocate file names for the temp results
%done_bengalese_name = cell(1,number_cells);
done_conspecific_name = cell(1,number_cells);
%done_flatrip_name = cell(1,number_cells);

for nc=1:number_cells
    %stimtype = 'bengalese';
    %done_bengalese_name{nc} = sprintf('%s_%s_%s_%s.mat' , mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
    stimtype = 'conspecific';
    done_conspecific_name{nc} = sprintf('%s_%s_%s_%s.mat' , mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
    %stimtype = 'flatrip';
    %done_flatrip_name{nc} = sprintf('%s_%s_%s_%s.mat' , mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);

end

not_done = 1;
n_loop = 0;
njobs = 0;
% Add jobs to queue until done
while not_done
    not_done = 0;
    for nc=1:number_cells
        %stimtype = 'bengalese';
        %if (exist(done_bengalese_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
        stimtype = 'conspecific';
        if (exist(done_conspecific_name{nc},'file') == 0)
            the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
            the_comment = sprintf('ND%s%s%s%s',mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
            njobs = njobs +1;
            qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
            not_done = 1;
            if n_loop
                fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
            end
        end
        %stimtype = 'flatrip';
        %if (exist(done_flatrip_name{nc},'file') == 0)
        %    the_command = sprintf('cd(''/auto/fhome/smunro/matlab/Neural Discrimination''); neural_discrimination_queue(''%s'', ''%s'', ''%s'', ''%s'')', mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
        %    the_comment = sprintf('ND%s%s%s%s',mld_xf{nc}{1}, brainregion, mld_xf{nc}{2}, stimtype);
        %    njobs = njobs +1;
        %    qid_submitted(njobs) = dbaddqueuemaster(the_command, the_comment);
        %    not_done = 1;
        %    if n_loop
        %        fprintf(1, 'Job %s not finished after loop %d\n', the_comment, n_loop);
        %    end
        %end
    end
    if (not_done)
        pause(40*60); % pause for 40 minutes
    end
    n_loop = n_loop +1;
end

% Clean the queue
for ij=1:njobs
    silent_dbdeletequeue(qid_submitted(ij));
end

% Print the results to a text file
%nstim = 3;
nstim = 1;
%stim_type = {'bengalese', 'conspecific', 'flatrip'};
stim_type = {'conspecific'};
all_outputs = cell(number_cells, nstim);

for nc=1:number_cells
    %load(done_bengalese_name{nc});
    %all_outputs{nc,1} = outputs;
    
    load(done_conspecific_name{nc});
    all_outputs{nc,2} = outputs;
    
    %load(done_flatrip_name{nc});
    %all_outputs{nc,3} = outputs;
end
save(fname, 'nstim', 'stim_type', 'mld_xf', 'all_outputs');