#!/bin/bash

function run_bird {

    bird_name=$1
    tank_root=$2
    stim_root=$3

    tank_dir="$tank_root/$bird_name"
    stim_file="$stim_root/$bird_name/stimProtocol.txt"
    bmap_file="/auto/fdata/julie/block_mapping_files.csv"
    output_dir="/tmp/tdt2hdf5/solveig/$bird_name"
    log_file="$output_dir/tdt2hdf5.log"

    rm -fr $output_dir
    mkdir -p $output_dir

    python convert_tank.py --tank_dir $tank_dir --stim_file $stim_file --block_mapping_file $bmap_file --output_dir $output_dir --check_zscore 0 &> $log_file &
}

troot="/auto/fdata/solveig/ELECTROPHY/Export_Data"
sroot="/auto/fdata/solveig/ELECTROPHY/Stims"

#for bname in "BlaLb1986M" "GreWhi2513F"
#for bname in "GreWhi2513F" "BlaLb1986M" "GraBla1602F" "BluBlu1221M"
for bname in "GreWhi2513F" "BlaLbl1986M" "GraBla1602F" "BluBlu1221M" "GraBla1703F" "GraGre1804M" "WhiWhi1009F" "WhiWhi4826M"
do
    run_bird $bname $troot $sroot
done
